package coder

import (
	"fmt"
	"os"
	"strings"
)

// Coder defines the interface for creating files based on a spec
type Coder interface {
	Build(specPath string) error
}

// MockCoder reads the spec and generates a dummy code file
type MockCoder struct {
	OutputFile string
}

// NewMockCoder creates a new mock coder
func NewMockCoder(outputFile string) *MockCoder {
	return &MockCoder{
		OutputFile: outputFile,
	}
}

// Build simulates code generation
func (mc *MockCoder) Build(specPath string) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return fmt.Errorf("could not read spec: %w", err)
	}

	specContent := string(data)
	// Find prompt in spec
	var prompt string
	lines := strings.Split(specContent, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "Generated from prompt: ") {
			prompt = strings.TrimPrefix(line, "Generated from prompt: ")
			break
		}
	}

	if prompt == "" {
		prompt = "Unknown Task"
	}

	code := fmt.Sprintf("// Automatically generated by Ralph2\n// Source: %s\n\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"Implemented logic for: %s\")\n}\n", specPath, prompt)
	
	err = os.WriteFile(mc.OutputFile, []byte(code), 0644)
	if err != nil {
		return fmt.Errorf("failed to write code: %w", err)
	}

	return nil
}
